=== ska-telescope/sdp-proccontrol/src/processing_controller/processing_controller/schema/workflows.json
{
  "$id": "https://gitlab.com/ska-telescope/sdp-prototype/blob/master/src/processing_controller/workflow_schema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "description": "Schema for SDP Prototype workflow definition file",
  "required": [
    "version",
    "repositories",
    "workflows"
  ],
  "optional":[
    "about"
  ],
  "definitions": {},
  "additionalProperties": false,
  "properties": {
    "about": {
      "$id": "#/properties/about",
      "type": "array",
      "items": {
        "$id": "#/properties/about/items",
        "type": "string",
        "examples": [
          "SDP Processing Controller workflow image definitions"
        ],
        "pattern": "^(.*)$"
      }
    },
    "version": {
      "$id": "#/properties/version",
      "type": "object",
      "required": [
        "date-time"
      ],
      "properties": {
        "date-time": {
          "$id": "#/properties/version/properties/date-time",
          "type": "string",
          "examples": [
            "2019-10-26T10:25:00Z"
          ],
          "pattern": "^(.*)$"
        }
      }
    },
    "repositories": {
      "$id": "#/properties/repositories",
      "type": "array",
      "minItems": 1,
      "items": {
        "$id": "#/properties/repositories/items",
        "type": "object",
        "required": [
          "name",
          "path"
        ],
        "additionalProperties": false,
        "properties": {
          "name": {
            "$id": "#/properties/repositories/items/properties/name",
            "type": "string",
            "examples": [
              "nexus"
            ],
            "pattern": "^(.*)$"
          },
          "path": {
            "$id": "#/properties/repositories/items/properties/path",
            "type": "string",
            "examples": [
              "nexus.engageska-portugal.pt/sdp-prototype"
            ],
            "pattern": "^(.*)$"
          }
        }
      }
    },
    "workflows": {
      "$id": "#/properties/workflows",
      "type": "array",
      "minItems": 1,
      "items": {
        "$id": "#/properties/workflows/items",
        "type": "object",
        "required": [
          "id",
          "repository",
          "image",
          "versions"
        ],
        "additionalProperties": false,
        "properties": {
          "type": {
            "$id": "#/properties/workflows/items/properties/type",
            "type": "string",
            "examples": [
              "realtime",
              "batch"
            ],
            "pattern": "^(realtime)|(batch)$"
          },
          "id": {
            "$id": "#/properties/workflows/items/properties/id",
            "type": "string",
            "examples": [
              "test1"
            ],
            "pattern": "^(.*)$"
          },
          "repository": {
            "$id": "#/properties/workflows/items/properties/repository",
            "type": "string",
            "examples": [
              "nexus"
            ],
            "pattern": "^(.*)$"
          },
          "image": {
            "$id": "#/properties/workflows/items/properties/image",
            "type": "string",
            "examples": [
              "workflow-test1"
            ],
            "pattern": "^(.*)$"
          },
          "versions": {
            "$id": "#/properties/workflows/items/properties/versions",
            "type": "array",
            "minItems": 1,
            "items": {
              "$id": "#/properties/workflows/items/properties/versions/items",
              "type": "string",
              "examples": [
                "1.0.0",
                "1.1.0"
              ],
              "pattern": "^(.*)$"
            }
          }
        }
      }
    }
  }
}

=== ska-telescope/sdp-proccontrol/src/processing_controller/test/data/workflows.json
{
  "about": [
    "SDP Processing Controller workflow image definitions"
  ],
  "version": {
    "date-time": "2020-04-25T15:00:00Z"
  },
  "repositories": [
    {"name": "nexus", "path": "nexus.engageska-portugal.pt/sdp-prototype"}
  ],
  "workflows": [
    {"type": "batch", "id":  "test_batch", "repository": "nexus", "image": "workflow-test-batch", "versions": ["0.2.1"]},
    {"type": "realtime", "id":  "test_realtime", "repository": "nexus", "image": "workflow-test-realtime", "versions": ["0.2.1"]}
  ]
}
