=== ska-telescope/sdp-proccontrol/src/processing_controller/workflows_schema.json
{
  "$id": "https://gitlab.com/ska-telescope/sdp-prototype/blob/master/src/processing_controller/workflow_schema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "description": "Schema for SDP Prototype workflow definition file",
  "required": [
    "version",
    "repositories",
    "realtime",
    "batch"
  ],
  "optional":[
    "about"
  ],
  "definitions": {},
  "additionalProperties": false,
  "properties": {
    "about": {
      "$id": "#/properties/about",
      "type": "array",
      "items": {
        "$id": "#/properties/about/items",
        "type": "string",
        "examples": [
          "SDP Processing Controller workflow image definitions"
        ],
        "pattern": "^(.*)$"
      }
    },
    "version": {
      "$id": "#/properties/version",
      "type": "object",
      "required": [
        "date-time"
      ],
      "properties": {
        "date-time": {
          "$id": "#/properties/version/properties/date-time",
          "type": "string",
          "examples": [
            "2019-10-26T10:25:00Z"
          ],
          "pattern": "^(.*)$"
        }
      }
    },
    "repositories": {
      "$id": "#/properties/repositories",
      "type": "array",
      "minItems": 1,
      "items": {
        "$id": "#/properties/repositories/items",
        "type": "object",
        "required": [
          "name",
          "path"
        ],
        "additionalProperties": false,
        "properties": {
          "name": {
            "$id": "#/properties/repositories/items/properties/name",
            "type": "string",
            "examples": [
              "nexus"
            ],
            "pattern": "^(.*)$"
          },
          "path": {
            "$id": "#/properties/repositories/items/properties/path",
            "type": "string",
            "examples": [
              "nexus.engageska-portugal.pt/sdp-prototype"
            ],
            "pattern": "^(.*)$"
          }
        }
      }
    },
    "realtime": {
      "$id": "#/properties/realtime",
      "type": "array",
      "minItems": 1,
      "items": {
        "$id": "#/properties/realtime/items",
        "type": "object",
        "required": [
          "id",
          "repository",
          "image",
          "versions"
        ],
        "additionalProperties": false,
        "properties": {
          "id": {
            "$id": "#/properties/realtime/items/properties/id",
            "type": "string",
            "examples": [
              "test1"
            ],
            "pattern": "^(.*)$"
          },
          "repository": {
            "$id": "#/properties/realtime/items/properties/repository",
            "type": "string",
            "examples": [
              "nexus"
            ],
            "pattern": "^(.*)$"
          },
          "image": {
            "$id": "#/properties/realtime/items/properties/image",
            "type": "string",
            "examples": [
              "workflow-test1"
            ],
            "pattern": "^(.*)$"
          },
          "versions": {
            "$id": "#/properties/realtime/items/properties/versions",
            "type": "array",
            "minItems": 1,
            "items": {
              "$id": "#/properties/realtime/items/properties/versions/items",
              "type": "string",
              "examples": [
                "1.0.0",
                "1.1.0"
              ],
              "pattern": "^(.*)$"
            }
          }
        }
      }
    },
    "batch": {
      "$id": "#/properties/batch",
      "type": "array",
      "items": {
        "$id": "#/properties/batch/items",
        "type": "object",
        "required": [
          "id",
          "repository",
          "image",
          "versions"
        ],
        "minItems": 0,
        "additionalProperties": false,
        "properties": {
          "id": {
            "$id": "#/properties/batch/items/properties/id",
            "type": "string",
            "examples": [
              "test2"
            ],
            "pattern": "^(.*)$"
          },
          "repository": {
            "$id": "#/properties/batch/items/properties/repository",
            "type": "string",
            "examples": [
              "nexus"
            ],
            "pattern": "^(.*)$"
          },
          "image": {
            "$id": "#/properties/batch/items/properties/image",
            "type": "string",
            "examples": [
              "workflow-test2"
            ],
            "pattern": "^(.*)$"
          },
          "versions": {
            "$id": "#/properties/batch/items/properties/versions",
            "type": "array",
            "minItems": 1,
            "items": {
              "$id": "#/properties/batch/items/properties/versions/items",
              "type": "string",
              "examples": [
                "2.0.0",
                "2.1.0"
              ],
              "pattern": "^(.*)$"
            }
          }
        }
      }
    }
  }
}

=== ska-telescope/sdp-proccontrol/src/processing_controller/workflows.json
{
  "about": [
    "SDP Processing Controller workflow image definitions"
  ],
  "version": {
    "date-time": "2019-10-28T19:00:00Z"
  },
  "repositories": [
    {"name": "nexus", "path": "nexus.engageska-portugal.pt/sdp-prototype"}
  ],
  "realtime": [
    {"id":  "testdask", "repository": "nexus", "image": "workflow-testdask", "versions": ["0.1.0"]},
    {"id":  "testdeploy", "repository": "nexus", "image": "workflow-testdeploy", "versions": ["0.1.0"]},
    {"id":  "testdlg", "repository": "nexus", "image": "workflow-testdlg", "versions": ["0.1.0"]},
    {"id":  "vis_receive", "repository": "nexus", "image": "workflow-vis-receive", "versions": ["0.1.0"]}
  ],
  "batch": []
}
